//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPITest.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IdUser { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int Sale { get; set; }
        public int Type { get; set; }
    
        public virtual Logins Logins { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
